; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = rp2040_adalogger

[env]
framework = arduino

[env:rp2040_adalogger]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_adalogger
board_build.core = earlephilhower
lib_deps = adafruit/Adafruit NeoPixel @ ^1.15.5

[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
board_build.core = earlephilhower