; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_adalogger]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_adalogger
board_build.core = earlephilhower

framework = arduino
lib_deps =
    adafruit/SdFat - Adafruit Fork @ ^2.3.103
    SerialMenu
    adafruit/Adafruit BNO08x @ ^1.2.5
    adafruit/Adafruit NeoPixel @ ^1.15.5
    adafruit/Adafruit BMP280 Library @ ^3.0.0
    adafruit/Adafruit BME280 Library @ ^2.3.0
    https://github.com/jordanfirthussf/zmodem_test#zmodem_class
